/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  "update your install command.", FutureWarning)
2023-02-22 16:03:55,251	INFO services.py:1274 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
2023-02-22 16:03:57,469	WARNING function_runner.py:545 -- Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.
[2m[36m(pid=354694)[0m 2023-02-22 16:04:01,059	INFO trainer.py:698 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
[2m[36m(pid=354694)[0m 2023-02-22 16:04:01,106	WARNING catalog.py:549 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']!
[2m[36m(pid=354694)[0m 2023-02-22 16:04:01,108	WARNING catalog.py:549 -- Custom ModelV2 should accept all custom options as **kwargs, instead of expecting them in config['custom_model_config']!
[2m[36m(pid=354694)[0m 2023-02-22 16:04:01,420	WARNING util.py:53 -- Install gputil for GPU system monitoring.
[2m[36m(pid=354694)[0m sh: 1: /home/cs20btech11018/repos/ML-Phase-Ordering/build/bin/llc: not found
[2m[36m(pid=354694)[0m Reading from /home/cs20btech11018/repos/POSET-RL/IR2Vec/seedEmbeddingVocab-300-llvm10.txt
[2m[36m(pid=354694)[0m sh: 1: /home/cs20btech11018/repos/ML-Phase-Ordering/build/bin/llc: not found
[2m[36m(pid=354694)[0m 2023-02-22 16:04:12,031	ERROR function_runner.py:254 -- Runner Thread raised error.
[2m[36m(pid=354694)[0m Traceback (most recent call last):
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 248, in run
[2m[36m(pid=354694)[0m     self._entrypoint()
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 316, in entrypoint
[2m[36m(pid=354694)[0m     self._status_reporter.get_checkpoint())
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 580, in _trainable_func
[2m[36m(pid=354694)[0m     output = fn()
[2m[36m(pid=354694)[0m   File "experiment.py", line 71, in experiment
[2m[36m(pid=354694)[0m     train_results = train_agent.train()
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 608, in train
[2m[36m(pid=354694)[0m     raise e
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 594, in train
[2m[36m(pid=354694)[0m     result = Trainable.train(self)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/trainable.py", line 232, in train
[2m[36m(pid=354694)[0m     result = self.step()
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 173, in step
[2m[36m(pid=354694)[0m     res = next(self.train_exec_impl)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
[2m[36m(pid=354694)[0m     return next(self.built_iterator)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 1075, in build_union
[2m[36m(pid=354694)[0m     item = next(it)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
[2m[36m(pid=354694)[0m     return next(self.built_iterator)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/execution/rollout_ops.py", line 74, in sampler
[2m[36m(pid=354694)[0m     yield workers.local_worker().sample()
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 726, in sample
[2m[36m(pid=354694)[0m     batches = [self.input_reader.next()]
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 99, in next
[2m[36m(pid=354694)[0m     batches = [self.get_data()]
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 226, in get_data
[2m[36m(pid=354694)[0m     item = next(self.rollout_provider)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 651, in _env_runner
[2m[36m(pid=354694)[0m     base_env.send_actions(actions_to_send)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 363, in send_actions
[2m[36m(pid=354694)[0m     self.vector_env.vector_step(action_vector)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/env/vector_env.py", line 167, in vector_step
[2m[36m(pid=354694)[0m     obs, r, done, info = self.envs[i].step(actions[i])
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/repos/ML-Phase-Ordering/Model/RLLib-PhaseOrder/Environment.py", line 204, in step
[2m[36m(pid=354694)[0m     Reward, NextStateIR = self.getLocalReward(action_index)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/repos/ML-Phase-Ordering/Model/RLLib-PhaseOrder/Environment.py", line 321, in getLocalReward
[2m[36m(pid=354694)[0m     mca_cost = (self.OzMcaThroughtput - currMcaThroughtput) / self.OzMcaThroughtput
[2m[36m(pid=354694)[0m ZeroDivisionError: division by zero
[2m[36m(pid=354694)[0m Exception in thread Thread-2:
[2m[36m(pid=354694)[0m Traceback (most recent call last):
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
[2m[36m(pid=354694)[0m     self.run()
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 267, in run
[2m[36m(pid=354694)[0m     raise e
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 248, in run
[2m[36m(pid=354694)[0m     self._entrypoint()
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 316, in entrypoint
[2m[36m(pid=354694)[0m     self._status_reporter.get_checkpoint())
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 580, in _trainable_func
[2m[36m(pid=354694)[0m     output = fn()
[2m[36m(pid=354694)[0m   File "experiment.py", line 71, in experiment
[2m[36m(pid=354694)[0m     train_results = train_agent.train()
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 608, in train
[2m[36m(pid=354694)[0m     raise e
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 594, in train
[2m[36m(pid=354694)[0m     result = Trainable.train(self)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/trainable.py", line 232, in train
[2m[36m(pid=354694)[0m     result = self.step()
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 173, in step
[2m[36m(pid=354694)[0m     res = next(self.train_exec_impl)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
[2m[36m(pid=354694)[0m     return next(self.built_iterator)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 1075, in build_union
[2m[36m(pid=354694)[0m     item = next(it)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
[2m[36m(pid=354694)[0m     return next(self.built_iterator)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
[2m[36m(pid=354694)[0m     for item in it:
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/execution/rollout_ops.py", line 74, in sampler
[2m[36m(pid=354694)[0m     yield workers.local_worker().sample()
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 726, in sample
[2m[36m(pid=354694)[0m     batches = [self.input_reader.next()]
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 99, in next
[2m[36m(pid=354694)[0m     batches = [self.get_data()]
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 226, in get_data
[2m[36m(pid=354694)[0m     item = next(self.rollout_provider)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 651, in _env_runner
[2m[36m(pid=354694)[0m     base_env.send_actions(actions_to_send)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 363, in send_actions
[2m[36m(pid=354694)[0m     self.vector_env.vector_step(action_vector)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/env/vector_env.py", line 167, in vector_step
[2m[36m(pid=354694)[0m     obs, r, done, info = self.envs[i].step(actions[i])
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/repos/ML-Phase-Ordering/Model/RLLib-PhaseOrder/Environment.py", line 204, in step
[2m[36m(pid=354694)[0m     Reward, NextStateIR = self.getLocalReward(action_index)
[2m[36m(pid=354694)[0m   File "/home/cs20btech11018/repos/ML-Phase-Ordering/Model/RLLib-PhaseOrder/Environment.py", line 321, in getLocalReward
[2m[36m(pid=354694)[0m     mca_cost = (self.OzMcaThroughtput - currMcaThroughtput) / self.OzMcaThroughtput
[2m[36m(pid=354694)[0m ZeroDivisionError: division by zero
[2m[36m(pid=354694)[0m 
2023-02-22 16:04:12,054	ERROR trial_runner.py:748 -- Trial experiment_PhaseOrder_69a03_00000: Error processing event.
Traceback (most recent call last):
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 718, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 688, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/worker.py", line 1494, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): [36mray::ImplicitFunc.train_buffered()[39m (pid=354694, ip=192.168.50.101)
  File "python/ray/_raylet.pyx", line 501, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 451, in ray._raylet.execute_task.function_executor
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/_private/function_manager.py", line 563, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/trainable.py", line 173, in train_buffered
    result = self.train()
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 366, in step
    self._report_thread_runner_error(block=True)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 513, in _report_thread_runner_error
    ("Trial raised an exception. Traceback:\n{}".format(err_tb_str)
ray.tune.error.TuneError: Trial raised an exception. Traceback:
[36mray::ImplicitFunc.train_buffered()[39m (pid=354694, ip=192.168.50.101)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 248, in run
    self._entrypoint()
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 316, in entrypoint
    self._status_reporter.get_checkpoint())
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/function_runner.py", line 580, in _trainable_func
    output = fn()
  File "experiment.py", line 71, in experiment
    train_results = train_agent.train()
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 608, in train
    raise e
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/agents/trainer.py", line 594, in train
    result = Trainable.train(self)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/trainable.py", line 232, in train
    result = self.step()
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py", line 173, in step
    res = next(self.train_exec_impl)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 843, in apply_filter
    for item in it:
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 1075, in build_union
    item = next(it)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/util/iter.py", line 783, in apply_foreach
    for item in it:
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/execution/rollout_ops.py", line 74, in sampler
    yield workers.local_worker().sample()
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py", line 726, in sample
    batches = [self.input_reader.next()]
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 99, in next
    batches = [self.get_data()]
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 226, in get_data
    item = next(self.rollout_provider)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py", line 651, in _env_runner
    base_env.send_actions(actions_to_send)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/env/base_env.py", line 363, in send_actions
    self.vector_env.vector_step(action_vector)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/rllib/env/vector_env.py", line 167, in vector_step
    obs, r, done, info = self.envs[i].step(actions[i])
  File "/home/cs20btech11018/repos/ML-Phase-Ordering/Model/RLLib-PhaseOrder/Environment.py", line 204, in step
    Reward, NextStateIR = self.getLocalReward(action_index)
  File "/home/cs20btech11018/repos/ML-Phase-Ordering/Model/RLLib-PhaseOrder/Environment.py", line 321, in getLocalReward
    mca_cost = (self.OzMcaThroughtput - currMcaThroughtput) / self.OzMcaThroughtput
ZeroDivisionError: division by zero
== Status ==
Memory usage on this node: 58.4/125.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/72 CPUs, 0/0 GPUs, 0.0/42.87 GiB heap, 0.0/21.43 GiB objects
Result logdir: /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch
Number of trials: 1/1 (1 PENDING)
+-----------------------------------+----------+-------+
| Trial name                        | status   | loc   |
|-----------------------------------+----------+-------|
| experiment_PhaseOrder_69a03_00000 | PENDING  |       |
+-----------------------------------+----------+-------+


[2m[36m(pid=354694)[0m Number of files 141
[2m[36m(pid=354694)[0m Curr_Dir /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector
[2m[36m(pid=354694)[0m /home/cs20btech11018/repos/ML-Phase-Ordering/build/bin/clang  -c /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector.ll -o /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/base_binary.o
[2m[36m(pid=354694)[0m base 138256
[2m[36m(pid=354694)[0m /home/cs20btech11018/repos/ML-Phase-Ordering/build/bin/opt  -S -Oz /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector.ll -o /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector_Oz.ll
[2m[36m(pid=354694)[0m /home/cs20btech11018/repos/ML-Phase-Ordering/build/bin/clang  -c /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector_Oz.ll -o /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Oz_binary.o
[2m[36m(pid=354694)[0m llc: /home/cs20btech11018/repos/ML-Phase-Ordering/build/bin/llc  /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector_Oz.ll -o /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector_Oz.s
[2m[36m(pid=354694)[0m command: /home/cs20btech11018/repos/ML-Phase-Ordering/build/bin/llvm-mca  /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector_Oz.s
[2m[36m(pid=354694)[0m error: /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector_Oz.s: No such file or directory
[2m[36m(pid=354694)[0m 
[2m[36m(pid=354694)[0m LLVM-MCA command: /home/cs20btech11018/repos/ML-Phase-Ordering/build/bin/llvm-mca  /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector_Oz.s
[2m[36m(pid=354694)[0m base 0
[2m[36m(pid=354694)[0m fileName Adobe-C++-stepanov_vector
[2m[36m(pid=354694)[0m StateIndex 1
[2m[36m(pid=354694)[0m BaseIR /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector.ll
[2m[36m(pid=354694)[0m lastBinarySize 138256
[2m[36m(pid=354694)[0m currBinarySize 146344
[2m[36m(pid=354694)[0m llc: /home/cs20btech11018/repos/ML-Phase-Ordering/build/bin/llc  /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector_1.ll -o /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector_1.s
[2m[36m(pid=354694)[0m command: /home/cs20btech11018/repos/ML-Phase-Ordering/build/bin/llvm-mca  /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector_1.s
[2m[36m(pid=354694)[0m error: /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector_1.s: No such file or directory
[2m[36m(pid=354694)[0m 
[2m[36m(pid=354694)[0m LLVM-MCA command: /home/cs20btech11018/repos/ML-Phase-Ordering/build/bin/llvm-mca  /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/env/Adobe-C++-stepanov_vector/Adobe-C++-stepanov_vector_1.s
[2m[36m(pid=354694)[0m currMcaThroughtput: 0
[2m[36m(pid=354694)[0m OzMcaThroughtput: 0
[2m[36m(pid=354694)[0m lastMcaThroughtput: None
Result for experiment_PhaseOrder_69a03_00000:
  {}
  
== Status ==
Memory usage on this node: 58.7/125.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/72 CPUs, 0/0 GPUs, 0.0/42.87 GiB heap, 0.0/21.43 GiB objects
Result logdir: /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch
Number of trials: 1/1 (1 ERROR)
+-----------------------------------+----------+-------+
| Trial name                        | status   | loc   |
|-----------------------------------+----------+-------|
| experiment_PhaseOrder_69a03_00000 | ERROR    |       |
+-----------------------------------+----------+-------+
Number of errored trials: 1
+-----------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------------+
| Trial name                        |   # failures | error file                                                                                                                       |
|-----------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------------|
| experiment_PhaseOrder_69a03_00000 |            1 | /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/error.txt |
+-----------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------------+

== Status ==
Memory usage on this node: 58.7/125.8 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/72 CPUs, 0/0 GPUs, 0.0/42.87 GiB heap, 0.0/21.43 GiB objects
Result logdir: /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch
Number of trials: 1/1 (1 ERROR)
+-----------------------------------+----------+-------+
| Trial name                        | status   | loc   |
|-----------------------------------+----------+-------|
| experiment_PhaseOrder_69a03_00000 | ERROR    |       |
+-----------------------------------+----------+-------+
Number of errored trials: 1
+-----------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------------+
| Trial name                        |   # failures | error file                                                                                                                       |
|-----------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------------|
| experiment_PhaseOrder_69a03_00000 |            1 | /home/cs20btech11018/ray_results/0.2thresh-10alpha-5beta-aarch/experiment_PhaseOrder_69a03_00000_0_2023-02-22_16-03-57/error.txt |
+-----------------------------------+--------------+----------------------------------------------------------------------------------------------------------------------------------+

Traceback (most recent call last):
  File "experiment.py", line 138, in <module>
    tune.run(experiment, config=config, resources_per_trial=DQNTrainer.default_resource_request(config), name=args.log_dir)
  File "/home/cs20btech11018/anaconda3/envs/rllib_env/lib/python3.7/site-packages/ray/tune/tune.py", line 543, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [experiment_PhaseOrder_69a03_00000])
